<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once ChatComposer's real design lands.
  const demoHtml: string = `<div class="chat-composer" aria-label="a chat input form with a text area that grows with its content, sends on Enter, and turns its send button into a stop button while a reply is in progress">ChatComposer</div>`;
</script>

<svelte:head>
  <title>ChatComposer — Lily Design System</title>
  <meta name="description" content="a chat input form with a text area that grows with its content, sends on Enter, and turns its send button into a stop button while a reply is in progress" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>ChatComposer</h1>
  <p>a chat input form with a text area that grows with its content, sends on Enter, and turns its send button into a stop button while a reply is in progress</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/chat-composer/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: chat-composer</li>
      <li>PascalCase: ChatComposer</li>
      <li>Description: a chat input form with a text area that grows with its content, sends on Enter, and turns its send button into a stop button while a reply is in progress</li>
      <li>Status: beta — implemented and unit-tested in all eight headless libraries; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;form&gt;</li>
      <li>CSS class: .chat-composer</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li>Textarea <code>aria-label</code> from <code>label</code>; the button is named by its visible word</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Enter: send. Shift+Enter: line break. Enter during IME composition: nothing. Enter/Space on the button: send or stop</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>label</code>, <code>sendLabel</code>, <code>stopLabel</code>: string (required)</li>
      <li><code>value</code>: string (bindable); <code>placeholder</code>, <code>name</code>: string; <code>minRows</code> (1), <code>maxRows</code> (8): number</li>
      <li><code>busy</code>, <code>disabled</code>: boolean (default <code>false</code>)</li>
      <li><code>onSend(value)</code>, <code>onStop()</code> (or <code>send</code> / <code>stop</code> events)</li>
      <li><code>children</code>: slot before the textarea; <code>class</code>, <code>...restProps</code> on the <code>&lt;form&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
