<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once MultiSelectWithExtras's real design lands.
  const demoHtml: string = `<div class="multi-select-with-extras" aria-label="a multiple-choice select with additional features like search, groups, or selected-value chips">MultiSelectWithExtras</div>`;
</script>

<svelte:head>
  <title>MultiSelectWithExtras — Lily Design System</title>
  <meta name="description" content="a multiple-choice select with additional features like search, groups, or selected-value chips" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>MultiSelectWithExtras</h1>
  <p>a multiple-choice select with additional features like search, groups, or selected-value chips</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/multi-select-with-extras/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: multi-select-with-extras</li>
      <li>PascalCase: MultiSelectWithExtras</li>
      <li>Description: a multiple-choice select with content before and after it</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;div&gt;</li>
      <li>CSS class: .multi-select-with-extras</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>aria-label=&#123;label&#125;</code> -- on the <code>&lt;select multiple&gt;</code>, provides its accessible name</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Native select keyboard behaviour only: Arrow keys move, Shift+Arrow extends selection, Tab moves focus</li>
      <li>Interactive content in <code>before</code> / <code>after</code> has its own native keyboard behaviour</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class on the wrapper</li>
      <li><code>label</code>: string (required) -- accessible name for the select</li>
      <li><code>value</code>: string[] (default: <code>[]</code>) -- bindable selected values</li>
      <li><code>size</code>: number (optional) -- visible rows</li>
      <li><code>required</code>: boolean (default: <code>false</code>)</li>
      <li><code>disabled</code>: boolean (default: <code>false</code>)</li>
      <li><code>children</code>: slot (required) -- <code>Option</code> elements</li>
      <li><code>before</code>: slot (optional) -- content before the select</li>
      <li><code>after</code>: slot (optional) -- content after the select</li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the wrapper <code>&lt;div&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
