// Lily component catalog — generated from components.tsv
// Components across HTML, Svelte, React, Vue, Angular, Blazor, Nunjucks headless

export type LilyComponent = {
  name: string;
  pascal: string;
  description: string;
  /** Maturity: see the rubric in spec/components. */
  status: 'stable' | 'beta' | 'experimental';
};

export const LILY_COMPONENTS: LilyComponent[] = [
  { name: "accordion-checkbox", pascal: "AccordionCheckbox", description: "a checkbox option that reveals an accordion panel when checked", status: "beta" },
  { name: "accordion-link", pascal: "AccordionLink", description: "an accordion link", status: "beta" },
  { name: "accordion-list", pascal: "AccordionList", description: "an accordion ordered list of list item components", status: "stable" },
  { name: "accordion-list-item", pascal: "AccordionListItem", description: "an accordion list item component", status: "stable" },
  { name: "accordion-nav", pascal: "AccordionNav", description: "an accordion navigation area for collapsible accordion information", status: "stable" },
  { name: "action-bar", pascal: "ActionBar", description: "a contextual action bar that appears when items are selected, showing the selection count and bulk action buttons", status: "beta" },
  { name: "action-bar-button", pascal: "ActionBarButton", description: "one action button inside an action bar", status: "beta" },
  { name: "action-group", pascal: "ActionGroup", description: "a group of action buttons that can collapse to an overflow menu when space is constrained", status: "beta" },
  { name: "action-link", pascal: "ActionLink", description: "a hyperlink styled as an action trigger", status: "stable" },
  { name: "address-input", pascal: "AddressInput", description: "an input for searching or manually entering an address", status: "beta" },
  { name: "addressograph-box", pascal: "AddressographBox", description: "a box that shows a person's identification details, such as name, tracking information, and salient notations", status: "experimental" },
  { name: "affix", pascal: "Affix", description: "a wrapper that pins its content to a viewport position while the page scrolls", status: "beta" },
  { name: "ai-label", pascal: "AiLabel", description: "an indicator of AI instances that is a pathway to AI explainability", status: "beta" },
  { name: "alba-community-health-index-input", pascal: "AlbaCommunityHealthIndexInput", description: "an input for entering Scotland's Community Health Index (CHI)", status: "beta" },
  { name: "alba-community-health-index-view", pascal: "AlbaCommunityHealthIndexView", description: "a read-only display of Scotland's Community Health Index (CHI)", status: "beta" },
  { name: "alert", pascal: "Alert", description: "a status message for important information or feedback", status: "beta" },
  { name: "alert-dialog", pascal: "AlertDialog", description: "a modal dialog for urgent messages requiring user acknowledgment", status: "stable" },
  { name: "angle-slider-range-input", pascal: "AngleSliderRangeInput", description: "a range input for selecting an angle in degrees", status: "beta" },
  { name: "announcement-banner", pascal: "AnnouncementBanner", description: "a banner highlighting important messages for all users", status: "beta" },
  { name: "answer", pascal: "Answer", description: "an answer is anything that responds to a question, request, action, etc.", status: "experimental" },
  { name: "area-chart", pascal: "AreaChart", description: "an area chart visualization showing sized components in continuous data", status: "beta" },
  { name: "article-layout", pascal: "ArticleLayout", description: "a top-level article wrapper that sets CSS custom properties for content column widths", status: "beta" },
  { name: "aspect-ratio-container", pascal: "AspectRatioContainer", description: "a container that maintains a fixed aspect ratio", status: "beta" },
  { name: "australia-individual-healthcare-identifier-input", pascal: "AustraliaIndividualHealthcareIdentifierInput", description: "an input for entering Australia's Individual Healthcare Identifier (IHI)", status: "beta" },
  { name: "australia-individual-healthcare-identifier-view", pascal: "AustraliaIndividualHealthcareIdentifierView", description: "a read-only display of Australia's Individual Healthcare Identifier (IHI)", status: "beta" },
  { name: "autosuggest", pascal: "Autosuggest", description: "a text input that proposes matching options as users type", status: "beta" },
  { name: "avatar", pascal: "Avatar", description: "an avatar indicator that shows an avatar image or avatar text", status: "stable" },
  { name: "avatar-group", pascal: "AvatarGroup", description: "a group of avatar components", status: "beta" },
  { name: "avatar-image", pascal: "AvatarImage", description: "an avatar indicator inside image such as a user photo", status: "stable" },
  { name: "avatar-text", pascal: "AvatarText", description: "an avatar indicator inner text such as a user name", status: "stable" },
  { name: "back-link", pascal: "BackLink", description: "a navigation link to return to a previous page", status: "stable" },
  { name: "badge", pascal: "Badge", description: "a small label for counts, statuses, or categories", status: "stable" },
  { name: "banner", pascal: "Banner", description: "a prominent message bar across the top of a page", status: "stable" },
  { name: "banner-box", pascal: "BannerBox", description: "a banner box that is inside a banner component, using flexbox horizontal", status: "beta" },
  { name: "bar-chart", pascal: "BarChart", description: "a horizontal bar chart visualization for displaying data", status: "beta" },
  { name: "barcode-image", pascal: "BarcodeImage", description: "a visual machine-readable symbolic code image, such as for a scanner", status: "experimental" },
  { name: "beach-ball", pascal: "BeachBall", description: "a decorative animated beach ball element", status: "beta" },
  { name: "belgique-numero-de-registre-national-input", pascal: "BelgiqueNumeroDeRegistreNationalInput", description: "an input for entering Belgium's Numéro de Registre National / Rijksregisternummer (NRN)", status: "beta" },
  { name: "belgique-numero-de-registre-national-view", pascal: "BelgiqueNumeroDeRegistreNationalView", description: "a read-only display of Belgium's Numéro de Registre National / Rijksregisternummer (NRN)", status: "beta" },
  { name: "blockquote", pascal: "Blockquote", description: "a block-level quotation with optional source citation", status: "beta" },
  { name: "body-text", pascal: "BodyText", description: "a rendered text block within a content width container", status: "beta" },
  { name: "breadcrumb-link", pascal: "BreadcrumbLink", description: "one breadcrumb link in the trail", status: "beta" },
  { name: "breadcrumb-list", pascal: "BreadcrumbList", description: "an ordered list of breadcrumb list items", status: "stable" },
  { name: "breadcrumb-list-item", pascal: "BreadcrumbListItem", description: "one breadcrumb list item in the trail", status: "stable" },
  { name: "breadcrumb-nav", pascal: "BreadcrumbNav", description: "a navigation container for breadcrumb trail links", status: "stable" },
  { name: "bulgaria-edinen-grazhdanski-nomer-input", pascal: "BulgariaEdinenGrazhdanskiNomerInput", description: "an input for entering Bulgaria's Единен граждански номер / Edinen grazhdanski nomer (EGN)", status: "beta" },
  { name: "bulgaria-edinen-grazhdanski-nomer-view", pascal: "BulgariaEdinenGrazhdanskiNomerView", description: "a read-only display of Bulgaria's Единен граждански номер / Edinen grazhdanski nomer (EGN)", status: "beta" },
  { name: "button", pascal: "Button", description: "a generic clickable button element", status: "stable" },
  { name: "button-group", pascal: "ButtonGroup", description: "a wrapper that groups related buttons together", status: "beta" },
  { name: "button-input", pascal: "ButtonInput", description: "an input element of type button for form actions <input type=\"button\">", status: "beta" },
  { name: "byline", pascal: "Byline", description: "an author attribution with publish and update timestamps", status: "beta" },
  { name: "calendar-range-picker", pascal: "CalendarRangePicker", description: "a picker for selecting a date range on a calendar", status: "beta" },
  { name: "calendar-table", pascal: "CalendarTable", description: "a calendar table interactive grid for managing dates, days, etc. <table>", status: "beta" },
  { name: "calendar-table-body", pascal: "CalendarTableBody", description: "a calendar table interactive grid tbody for managing dates, days, etc. <tbody>", status: "beta" },
  { name: "calendar-table-foot", pascal: "CalendarTableFoot", description: "a calendar table interactive grid tfoot for managing dates, days, etc. <tfoot>", status: "beta" },
  { name: "calendar-table-head", pascal: "CalendarTableHead", description: "a calendar table interactive grid thead for managing dates, days, etc. <thead>", status: "beta" },
  { name: "calendar-table-row", pascal: "CalendarTableRow", description: "a calendar table interactive grid row for managing dates, days, etc. <tr>", status: "beta" },
  { name: "calendar-table-td", pascal: "CalendarTableTD", description: "a calendar table interactive grid data cell for managing dates, days, etc. <td>", status: "beta" },
  { name: "calendar-table-th", pascal: "CalendarTableTH", description: "a calendar table interactive grid header cell for managing dates, days, etc. <th>", status: "beta" },
  { name: "call-to-action", pascal: "CallToAction", description: "a prominent prompt encouraging user action", status: "beta" },
  { name: "caption", pascal: "Caption", description: "a caption for a table or figure element", status: "stable" },
  { name: "card", pascal: "Card", description: "a grouped content container with header, body, and footer areas", status: "stable" },
  { name: "care-card", pascal: "CareCard", description: "a medical care instruction card with urgency levels", status: "stable" },
  { name: "carousel", pascal: "Carousel", description: "a slideshow for cycling through content items", status: "beta" },
  { name: "cascader", pascal: "Cascader", description: "a multi-level dropdown for selecting a value from a hierarchy", status: "beta" },
  { name: "cesko-cestovni-pas-input", pascal: "CeskoCestovniPasInput", description: "an input for entering Czech Republic's Cestovní pas", status: "beta" },
  { name: "cesko-cestovni-pas-view", pascal: "CeskoCestovniPasView", description: "a read-only display of Czech Republic's Cestovní pas", status: "beta" },
  { name: "cesko-rodne-cislo-input", pascal: "CeskoRodneCisloInput", description: "an input for entering Czech Republic's Rodné číslo (RČ)", status: "beta" },
  { name: "cesko-rodne-cislo-view", pascal: "CeskoRodneCisloView", description: "a read-only display of Czech Republic's Rodné číslo (RČ)", status: "beta" },
  { name: "character", pascal: "Character", description: "a single character display element", status: "stable" },
  { name: "character-counter", pascal: "CharacterCounter", description: "a counter showing remaining or used characters in a text field", status: "stable" },
  { name: "chat-list", pascal: "ChatList", description: "an ordered list of chat list item components", status: "beta" },
  { name: "chat-list-item", pascal: "ChatListItem", description: "one chat list item component, typically containing one chat message component", status: "beta" },
  { name: "chat-message", pascal: "ChatMessage", description: "a chat message shows one chat conversation message entry and all its data, including the author avatar, author name, time, etc.", status: "beta" },
  { name: "chat-nav", pascal: "ChatNav", description: "a navigation container for chat information", status: "beta" },
  { name: "check-list", pascal: "CheckList", description: "an ordered list of check list item components", status: "stable" },
  { name: "check-list-item", pascal: "CheckListItem", description: "one check list item component with a checkbox", status: "stable" },
  { name: "checkbox-group", pascal: "CheckboxGroup", description: "a group component that manages a collection of checkboxes with shared state", status: "beta" },
  { name: "checkbox-input", pascal: "CheckboxInput", description: "a checkbox input for toggling a boolean value <input type=\"checkbox\">", status: "stable" },
  { name: "citation", pascal: "Citation", description: "a citation acknowledges the relevance of a work of another to the topic of discussion", status: "beta" },
  { name: "clamp-text", pascal: "ClampText", description: "a text container that truncates content to a maximum number of lines", status: "beta" },
  { name: "clipboard-copy-button", pascal: "ClipboardCopyButton", description: "a button that copies text to the clipboard", status: "stable" },
  { name: "coachmark", pascal: "Coachmark", description: "an anchored popover that spotlights and explains a single feature", status: "beta" },
  { name: "code", pascal: "Code", description: "an inline code span for displaying short code snippets within surrounding text", status: "beta" },
  { name: "code-block", pascal: "CodeBlock", description: "a block of formatted code with optional line numbers and line highlighting", status: "beta" },
  { name: "collapsible", pascal: "Collapsible", description: "a container that can be expanded or collapsed", status: "stable" },
  { name: "collection-list", pascal: "CollectionList", description: "a compact list of multiple related items such as articles or events", status: "beta" },
  { name: "collection-list-item", pascal: "CollectionListItem", description: "one item in a collection list with optional image, heading, meta, and description", status: "beta" },
  { name: "color-input", pascal: "ColorInput", description: "an input for selecting a color value <input type=\"color\">", status: "stable" },
  { name: "color-picker", pascal: "ColorPicker", description: "a two-dimensional board for picking colors by hue and saturation", status: "beta" },
  { name: "color-picker-button", pascal: "ColorPickerButton", description: "a button showing a color swatch in a color picker", status: "beta" },
  { name: "column-chart", pascal: "ColumnChart", description: "a vertical column chart visualization for displaying data", status: "beta" },
  { name: "combobox", pascal: "Combobox", description: "a text input combined with a dropdown list for filtering options", status: "stable" },
  { name: "command", pascal: "Command", description: "a command palette for searching and executing actions", status: "beta" },
  { name: "comment", pascal: "Comment", description: "a comment is anything that expresses an opinion, observation, explanation, etc.", status: "experimental" },
  { name: "container", pascal: "Container", description: "a generic block-level content container", status: "beta" },
  { name: "container-with-fixed-width", pascal: "ContainerWithFixedWidth", description: "a centered content wrapper with a fixed max-width breakpoint", status: "beta" },
  { name: "container-with-fluid-width", pascal: "ContainerWithFluidWidth", description: "a full-width content wrapper with horizontal padding", status: "beta" },
  { name: "content-block", pascal: "ContentBlock", description: "a content width constraint container with named column widths", status: "beta" },
  { name: "contents-link", pascal: "ContentsLink", description: "one table of contents link", status: "beta" },
  { name: "contents-list", pascal: "ContentsList", description: "an contents ordered list of contents list item components", status: "stable" },
  { name: "contents-list-item", pascal: "ContentsListItem", description: "one contents list item", status: "stable" },
  { name: "contents-nav", pascal: "ContentsNav", description: "a contents navigation area", status: "stable" },
  { name: "context-menu", pascal: "ContextMenu", description: "a menu that appears on right-click or long-press", status: "stable" },
  { name: "context-menu-item", pascal: "ContextMenuItem", description: "one item in a context menu", status: "stable" },
  { name: "contextual-help", pascal: "ContextualHelp", description: "a help button that opens a popover with explanatory content", status: "beta" },
  { name: "currency-input", pascal: "CurrencyInput", description: "a locale-aware currency input with automatic formatting, symbols, separators", status: "beta" },
  { name: "cymru-rhif-y-gwasanaeth-iechyd-gwladol-input", pascal: "CymruRhifYGwasanaethIechydGwladolInput", description: "an input for entering Wales's Rhif y Gwasanaeth Iechyd Gwladol (Rhif GIG)", status: "beta" },
  { name: "cymru-rhif-y-gwasanaeth-iechyd-gwladol-view", pascal: "CymruRhifYGwasanaethIechydGwladolView", description: "a read-only display of Wales's Rhif y Gwasanaeth Iechyd Gwladol (Rhif GIG)", status: "beta" },
  { name: "cyprus-national-passport-number-input", pascal: "CyprusNationalPassportNumberInput", description: "an input for entering Cyprus's National Passport Number", status: "beta" },
  { name: "cyprus-national-passport-number-view", pascal: "CyprusNationalPassportNumberView", description: "a read-only display of Cyprus's National Passport Number", status: "beta" },
  { name: "danmark-personnummer-input", pascal: "DanmarkPersonnummerInput", description: "an input for entering Denmark's Personnummer (CPR-nummer) (CPR)", status: "beta" },
  { name: "danmark-personnummer-view", pascal: "DanmarkPersonnummerView", description: "a read-only display of Denmark's Personnummer (CPR-nummer) (CPR)", status: "beta" },
  { name: "data-filter-form", pascal: "DataFilterForm", description: "a form for filtering data by criteria", status: "beta" },
  { name: "data-table", pascal: "DataTable", description: "a data table interactive grid for displaying and sorting tabular data <table>", status: "stable" },
  { name: "data-table-body", pascal: "DataTableBody", description: "a data table interactive grid tbody for displaying and sorting tabular data <tbody>", status: "stable" },
  { name: "data-table-foot", pascal: "DataTableFoot", description: "a data table interactive grid tfoot for displaying and sorting tabular data <tfoot>", status: "beta" },
  { name: "data-table-head", pascal: "DataTableHead", description: "a data table interactive grid thead for displaying and sorting tabular data <thead>", status: "stable" },
  { name: "data-table-row", pascal: "DataTableRow", description: "a data table interactive grid row for displaying and sorting tabular data <tr>", status: "stable" },
  { name: "data-table-td", pascal: "DataTableTD", description: "a data table interactive grid data cell for displaying and sorting tabular data <td>", status: "stable" },
  { name: "data-table-th", pascal: "DataTableTH", description: "a data table interactive grid header cell for displaying and sorting tabular data <th>", status: "beta" },
  { name: "date-field", pascal: "DateField", description: "a structured field for entering date components", status: "beta" },
  { name: "date-input", pascal: "DateInput", description: "an input for entering a date value <input type=\"date\">", status: "stable" },
  { name: "date-range", pascal: "DateRange", description: "a display of a start and end date range", status: "stable" },
  { name: "date-time-local-input", pascal: "DateTimeLocalInput", description: "an input for entering a date and time without time zone <input type=\"datetime-local\">", status: "beta" },
  { name: "date-time-now-input", pascal: "DateTimeNowInput", description: "an input for entering a date and time and \"now\" button <input type=\"date\"><input type=\"time\"><button type=\"button\">", status: "beta" },
  { name: "date-time-view", pascal: "DateTimeView", description: "a read-only display of a formatted date and time", status: "beta" },
  { name: "description-list", pascal: "DescriptionList", description: "a definition list displaying information in key-value format <dl>", status: "beta" },
  { name: "description-list-item", pascal: "DescriptionListItem", description: "one key-value pair in a description list using dt and dd elements", status: "beta" },
  { name: "details", pascal: "Details", description: "a disclosure widget that shows and hides content", status: "stable" },
  { name: "deutschland-krankenversichertennummer-input", pascal: "DeutschlandKrankenversichertennummerInput", description: "an input for entering Germany's Krankenversichertennummer (KVNR)", status: "beta" },
  { name: "deutschland-krankenversichertennummer-view", pascal: "DeutschlandKrankenversichertennummerView", description: "a read-only display of Germany's Krankenversichertennummer (KVNR)", status: "beta" },
  { name: "dial", pascal: "Dial", description: "a rotary dial control for selecting a value", status: "beta" },
  { name: "dial-group", pascal: "DialGroup", description: "a group of dial components", status: "beta" },
  { name: "dialog", pascal: "Dialog", description: "a modal or non-modal dialog window", status: "stable" },
  { name: "diff", pascal: "Diff", description: "a side-by-side comparison of two items", status: "beta" },
  { name: "digital-object-identifier-link", pascal: "DigitalObjectIdentifierLink", description: "a permanent hyperlink for a Digital Object Identifier (DOI) to an electronic source", status: "beta" },
  { name: "do-list", pascal: "DoList", description: "a guideline list of encouraged do-list-item components", status: "stable" },
  { name: "do-list-item", pascal: "DoListItem", description: "an encouraged-practice item in a do-list guideline list", status: "stable" },
  { name: "document-list", pascal: "DocumentList", description: "a list displaying documents with titles and metadata", status: "beta" },
  { name: "document-list-item", pascal: "DocumentListItem", description: "one document entry in a document list", status: "beta" },
  { name: "dont-list", pascal: "DontList", description: "a guideline list of discouraged dont-list-item components", status: "stable" },
  { name: "dont-list-item", pascal: "DontListItem", description: "a discouraged-practice item in a dont-list guideline list", status: "stable" },
  { name: "download-button", pascal: "DownloadButton", description: "a download link styled as a button, with optional file size and format metadata", status: "beta" },
  { name: "draft", pascal: "Draft", description: "an early preliminary version of content such as an article, email, report, etc.", status: "experimental" },
  { name: "drawer", pascal: "Drawer", description: "a panel that slides in from the edge of the screen", status: "stable" },
  { name: "dropdown-menu", pascal: "DropdownMenu", description: "a menu that opens below a trigger button", status: "stable" },
  { name: "editable", pascal: "Editable", description: "an inline-editable text element that toggles between view and edit modes", status: "stable" },
  { name: "editable-form", pascal: "EditableForm", description: "a form wrapper for inline editing of content", status: "beta" },
  { name: "eesti-isikukood-input", pascal: "EestiIsikukoodInput", description: "an input for entering Estonia's Isikukood (IK)", status: "beta" },
  { name: "eesti-isikukood-view", pascal: "EestiIsikukoodView", description: "a read-only display of Estonia's Isikukood (IK)", status: "beta" },
  { name: "ellada-dematerialised-securities-system-input", pascal: "ElladaDematerialisedSecuritiesSystemInput", description: "an input for entering Greece's Dematerialised Securities System (DSS)", status: "beta" },
  { name: "ellada-dematerialised-securities-system-view", pascal: "ElladaDematerialisedSecuritiesSystemView", description: "a read-only display of Greece's Dematerialised Securities System (DSS)", status: "beta" },
  { name: "email-input", pascal: "EmailInput", description: "an input for entering an email address <input type=\"email\">", status: "stable" },
  { name: "email-link", pascal: "EmailLink", description: "a mailto hyperlink for an email address", status: "beta" },
  { name: "emoji", pascal: "Emoji", description: "a single emoji character with accessible name", status: "stable" },
  { name: "emoji-character-picker", pascal: "EmojiCharacterPicker", description: "a picker for browsing and selecting emoji characters", status: "beta" },
  { name: "end-notes", pascal: "EndNotes", description: "a section of titled endnote items at the end of an article", status: "beta" },
  { name: "england-national-health-service-number-input", pascal: "EnglandNationalHealthServiceNumberInput", description: "an input for entering England's National Health Service Number (NHS)", status: "beta" },
  { name: "england-national-health-service-number-view", pascal: "EnglandNationalHealthServiceNumberView", description: "a read-only display of England's National Health Service Number (NHS)", status: "beta" },
  { name: "error-message", pascal: "ErrorMessage", description: "an error message associated with a form field", status: "stable" },
  { name: "error-summary", pascal: "ErrorSummary", description: "a summary of all validation errors on a form", status: "stable" },
  { name: "espana-codigo-de-identificacion-fiscal-input", pascal: "EspanaCodigoDeIdentificacionFiscalInput", description: "an input for entering Spain's Código de Identificación Fiscal (CIF)", status: "beta" },
  { name: "espana-codigo-de-identificacion-fiscal-view", pascal: "EspanaCodigoDeIdentificacionFiscalView", description: "a read-only display of Spain's Código de Identificación Fiscal (CIF)", status: "beta" },
  { name: "espana-tarjeta-sanitaria-individual-input", pascal: "EspanaTarjetaSanitariaIndividualInput", description: "an input for entering an España Tarjeta Sanitaria Individual (TSI) unique national healthcare identifier", status: "beta" },
  { name: "espana-tarjeta-sanitaria-individual-view", pascal: "EspanaTarjetaSanitariaIndividualView", description: "a read-only display of an España Tarjeta Sanitaria Individual (TSI) unique national healthcare identifier", status: "beta" },
  { name: "event", pascal: "Event", description: "an event component that contains other event-related information", status: "beta" },
  { name: "expander", pascal: "Expander", description: "a control that expands to reveal more content", status: "stable" },
  { name: "feature-card", pascal: "FeatureCard", description: "a large content card with a prominent image positioned alongside or above the text", status: "beta" },
  { name: "feature-photo", pascal: "FeaturePhoto", description: "a responsive photo with lazy loading and alt text validation", status: "beta" },
  { name: "field", pascal: "Field", description: "a form field wrapper with label, input, and error message", status: "stable" },
  { name: "fieldset", pascal: "Fieldset", description: "a group of related form fields with a legend", status: "stable" },
  { name: "figure", pascal: "Figure", description: "a self-contained figure with optional caption", status: "stable" },
  { name: "file-dialog", pascal: "FileDialog", description: "a dialog for browsing and selecting files", status: "beta" },
  { name: "file-input", pascal: "FileInput", description: "an input for selecting files from the file system <input type=\"file\">", status: "stable" },
  { name: "file-manager", pascal: "FileManager", description: "a file browser for navigating and managing files", status: "beta" },
  { name: "file-upload", pascal: "FileUpload", description: "a drag-and-drop area for uploading files", status: "stable" },
  { name: "five-face-rating-picker", pascal: "FiveFaceRatingPicker", description: "a picker for selecting a 1-5 satisfaction rating using face labels", status: "stable" },
  { name: "five-face-rating-picker-button", pascal: "FiveFaceRatingPickerButton", description: "a picker button for selecting a 1-5 satisfaction rating using face labels", status: "beta" },
  { name: "five-face-rating-view", pascal: "FiveFaceRatingView", description: "a read-only display of a five-face satisfaction rating", status: "stable" },
  { name: "five-star-rating-picker", pascal: "FiveStarRatingPicker", description: "a picker for selecting a 1-5 star rating using radio buttons", status: "stable" },
  { name: "five-star-rating-picker-button", pascal: "FiveStarRatingPickerButton", description: "a picker button for selecting a 1-5 star rating using radio buttons", status: "beta" },
  { name: "five-star-rating-view", pascal: "FiveStarRatingView", description: "a read-only display of a five-star rating", status: "stable" },
  { name: "flair", pascal: "Flair", description: "a decorative highlight or emphasis element", status: "stable" },
  { name: "flex-stack", pascal: "FlexStack", description: "a flex layout container for vertical or horizontal stacking with consistent gap", status: "beta" },
  { name: "float-button", pascal: "FloatButton", description: "a floating action button anchored to a viewport corner", status: "beta" },
  { name: "floating-panel", pascal: "FloatingPanel", description: "a panel that floats above page content", status: "stable" },
  { name: "footer", pascal: "Footer", description: "a page or section footer area", status: "stable" },
  { name: "footnote", pascal: "Footnote", description: "a footnote reference and content element", status: "stable" },
  { name: "form", pascal: "Form", description: "a form element for collecting and submitting user data", status: "stable" },
  { name: "framer", pascal: "Framer", description: "a container for framed content display with decorative border", status: "beta" },
  { name: "france-numero-d-identification-au-repertoire-input", pascal: "FranceNumeroDIdentificationAuRepertoireInput", description: "an input for entering a France numéro d'identification au répertoire (NIR) unique national healthcare identifier", status: "beta" },
  { name: "france-numero-d-identification-au-repertoire-view", pascal: "FranceNumeroDIdentificationAuRepertoireView", description: "a read-only display of a France numéro d'identification au répertoire (NIR) unique national healthcare identifier", status: "beta" },
  { name: "gantt-table", pascal: "GanttTable", description: "a Gantt chart table interactive grid for planning schedule visualization <table>", status: "beta" },
  { name: "gantt-table-tbody", pascal: "GanttTableTbody", description: "a Gantt chart table interactive grid tbody for planning schedule visualization <tbody>", status: "beta" },
  { name: "gantt-table-td", pascal: "GanttTableTD", description: "a Gantt chart table interactive grid data cell for planning schedule visualization <td>", status: "beta" },
  { name: "gantt-table-tfoot", pascal: "GanttTableTfoot", description: "a Gantt chart table interactive grid tfoot for planning schedule visualization <tfoot>", status: "beta" },
  { name: "gantt-table-th", pascal: "GanttTableTH", description: "a Gantt chart table interactive grid header cell for planning schedule visualization <th>", status: "beta" },
  { name: "gantt-table-thead", pascal: "GanttTableThead", description: "a Gantt chart table interactive grid thead for planning schedule visualization <thead>", status: "beta" },
  { name: "gantt-table-tr", pascal: "GanttTableTr", description: "a Gantt chart table interactive grid row for planning schedule visualization <tr>", status: "beta" },
  { name: "go-to-next-section", pascal: "GoToNextSection", description: "a link that takes users to the next section of the current page", status: "beta" },
  { name: "go-to-previous-section", pascal: "GoToPreviousSection", description: "a link that takes users to the previous section of the current page", status: "beta" },
  { name: "go-to-top", pascal: "GoToTop", description: "a link that returns users to the top of a long page", status: "beta" },
  { name: "government-banner", pascal: "GovernmentBanner", description: "a banner identifying a website as belonging to a government, with an expandable details panel", status: "beta" },
  { name: "government-identifier", pascal: "GovernmentIdentifier", description: "an identifier section with a parent agency logo, agency name, and required government links", status: "beta" },
  { name: "grail-layout", pascal: "GrailLayout", description: "a responsive web design structure with header, left aside, center main, right aside, footer", status: "beta" },
  { name: "grail-layout-bottom-footer", pascal: "GrailLayoutBottomFooter", description: "grail layout bottom footer full width with <footer> tag", status: "beta" },
  { name: "grail-layout-center-main", pascal: "GrailLayoutCenterMain", description: "grail layout center main content with <main> tag", status: "beta" },
  { name: "grail-layout-left-aside", pascal: "GrailLayoutLeftAside", description: "grail layout left aside sidebar with <aside> tag", status: "beta" },
  { name: "grail-layout-right-aside", pascal: "GrailLayoutRightAside", description: "grail layout right aside sidebar with <aside> tag", status: "beta" },
  { name: "grail-layout-top-header", pascal: "GrailLayoutTopHeader", description: "grail layout top header full width with <header> tag", status: "beta" },
  { name: "graphic-block", pascal: "GraphicBlock", description: "a wrapper for charts and graphics with title, description, notes, and ARIA description", status: "beta" },
  { name: "grid", pascal: "Grid", description: "a CSS grid layout container with configurable columns and gap", status: "beta" },
  { name: "hamburger-menu", pascal: "HamburgerMenu", description: "a toggle button that opens a mobile navigation menu", status: "stable" },
  { name: "header", pascal: "Header", description: "a page or section header area", status: "stable" },
  { name: "headline", pascal: "Headline", description: "a page headline with heading, subtitle, and byline area", status: "beta" },
  { name: "hero", pascal: "Hero", description: "a large box or image with a title and description", status: "beta" },
  { name: "hero-headline", pascal: "HeroHeadline", description: "a full-bleed hero section with headline overlaid on media", status: "beta" },
  { name: "hidden-input", pascal: "HiddenInput", description: "a hidden input for including data in form submission <input type=\"hidden\">", status: "beta" },
  { name: "hint", pascal: "Hint", description: "hint text providing guidance for a form field", status: "stable" },
  { name: "horizontal-scroller", pascal: "HorizontalScroller", description: "a horizontally scrollable content container", status: "beta" },
  { name: "hover-card", pascal: "HoverCard", description: "a card that appears on hover over a trigger element", status: "stable" },
  { name: "hrvatska-osobni-identifikacijski-broj-input", pascal: "HrvatskaOsobniIdentifikacijskiBrojInput", description: "an input for entering Croatia's Osobni identifikacijski broj (OIB)", status: "beta" },
  { name: "hrvatska-osobni-identifikacijski-broj-view", pascal: "HrvatskaOsobniIdentifikacijskiBrojView", description: "a read-only display of Croatia's Osobni identifikacijski broj (OIB)", status: "beta" },
  { name: "icon", pascal: "Icon", description: "a container for displaying an icon", status: "stable" },
  { name: "icon-button", pascal: "IconButton", description: "a button containing only an icon with a required accessible label", status: "beta" },
  { name: "icon-list", pascal: "IconList", description: "an ordered list of icon list item components", status: "beta" },
  { name: "icon-list-item", pascal: "IconListItem", description: "one item in an icon list with a leading icon slot", status: "beta" },
  { name: "image", pascal: "Image", description: "an image element with alt text", status: "stable" },
  { name: "image-cropper", pascal: "ImageCropper", description: "a container for cropping and resizing an image to a selected region", status: "experimental" },
  { name: "image-file-input", pascal: "ImageFileInput", description: "an input for selecting image files with preview", status: "stable" },
  { name: "image-input", pascal: "ImageInput", description: "a graphical submit button that displays an image <input type=\"image\">", status: "beta" },
  { name: "info-state", pascal: "InfoState", description: "a composition of illustration, title, description, and action for empty, error, or info states", status: "beta" },
  { name: "information-callout", pascal: "InformationCallout", description: "a callout box highlighting informational content", status: "stable" },
  { name: "input", pascal: "Input", description: "a generic HTML input element", status: "beta" },
  { name: "input-group", pascal: "InputGroup", description: "a group wrapping an input with prefix and suffix addons", status: "beta" },
  { name: "input-with-mask", pascal: "InputWithMask", description: "an input displaying a format mask placeholder for the user to fill in", status: "beta" },
  { name: "inset-text", pascal: "InsetText", description: "indented text to distinguish it from surrounding content", status: "stable" },
  { name: "ireland-individual-health-identifier-input", pascal: "IrelandIndividualHealthIdentifierInput", description: "an input for entering Ireland Individual Health Identifier (IHI) unique national healthcare identifier", status: "beta" },
  { name: "ireland-individual-health-identifier-view", pascal: "IrelandIndividualHealthIdentifierView", description: "a read-only display of Ireland Individual Health Identifier (IHI) unique national healthcare identifier", status: "beta" },
  { name: "island-kennitala-input", pascal: "IslandKennitalaInput", description: "an input for entering Iceland's Kennitala", status: "beta" },
  { name: "island-kennitala-view", pascal: "IslandKennitalaView", description: "a read-only display of Iceland's Kennitala", status: "beta" },
  { name: "italia-codice-fiscale-input", pascal: "ItaliaCodiceFiscaleInput", description: "an input for entering Italy's Codice fiscale (CF)", status: "beta" },
  { name: "italia-codice-fiscale-view", pascal: "ItaliaCodiceFiscaleView", description: "a read-only display of Italy's Codice fiscale (CF)", status: "beta" },
  { name: "kanban-table", pascal: "KanbanTable", description: "a kanban board table interactive grid for organizing items by status <table>", status: "beta" },
  { name: "kanban-table-body", pascal: "KanbanTableBody", description: "a kanban board table interactive grid tbody for organizing items by status <tbody>", status: "beta" },
  { name: "kanban-table-foot", pascal: "KanbanTableFoot", description: "a kanban board table interactive grid tfoot for organizing items by status <tfoot>", status: "beta" },
  { name: "kanban-table-head", pascal: "KanbanTableHead", description: "a kanban board table interactive grid thead for organizing items by status <thead>", status: "beta" },
  { name: "kanban-table-row", pascal: "KanbanTableRow", description: "a kanban board table interactive grid row for organizing items by status <tr>", status: "beta" },
  { name: "kanban-table-td", pascal: "KanbanTableTD", description: "kanban board table interactive grid data cell for organizing items by status <td>", status: "beta" },
  { name: "kanban-table-th", pascal: "KanbanTableTH", description: "a kanban board table interactive grid header cell for organizing items by status <th>", status: "beta" },
  { name: "kbd", pascal: "Kbd", description: "show keyboard shortcuts and key combinations in a styled inline element", status: "beta" },
  { name: "label", pascal: "Label", description: "a label associated with a form input", status: "stable" },
  { name: "latvija-personas-kods-input", pascal: "LatvijaPersonasKodsInput", description: "an input for entering Latvia's Personas kods", status: "beta" },
  { name: "latvija-personas-kods-view", pascal: "LatvijaPersonasKodsView", description: "a read-only display of Latvia's Personas kods", status: "beta" },
  { name: "liechtenstein-national-identity-card-number-input", pascal: "LiechtensteinNationalIdentityCardNumberInput", description: "an input for entering Liechtenstein's Liechtenstein National Identity Card Number", status: "beta" },
  { name: "liechtenstein-national-identity-card-number-view", pascal: "LiechtensteinNationalIdentityCardNumberView", description: "a read-only display of Liechtenstein's Liechtenstein National Identity Card Number", status: "beta" },
  { name: "liechtenstein-passport-number-input", pascal: "LiechtensteinPassportNumberInput", description: "an input for entering Liechtenstein's Liechtenstein Passport Number", status: "beta" },
  { name: "liechtenstein-passport-number-view", pascal: "LiechtensteinPassportNumberView", description: "a read-only display of Liechtenstein's Liechtenstein Passport Number", status: "beta" },
  { name: "lietuva-asmens-kodas-input", pascal: "LietuvaAsmensKodasInput", description: "an input for entering Lithuania's Asmens kodas", status: "beta" },
  { name: "lietuva-asmens-kodas-view", pascal: "LietuvaAsmensKodasView", description: "a read-only display of Lithuania's Asmens kodas", status: "beta" },
  { name: "lietuva-pasas-input", pascal: "LietuvaPasasInput", description: "an input for entering Lithuania's Pasas", status: "beta" },
  { name: "lietuva-pasas-view", pascal: "LietuvaPasasView", description: "a read-only display of Lithuania's Pasas", status: "beta" },
  { name: "line-chart", pascal: "LineChart", description: "a line chart visualization connecting data points to display data", status: "beta" },
  { name: "listbox", pascal: "Listbox", description: "a list of selectable options with keyboard navigation", status: "stable" },
  { name: "loading", pascal: "Loading", description: "a loading indicator, such as text, or image, or animation", status: "beta" },
  { name: "malta-national-identification-number-input", pascal: "MaltaNationalIdentificationNumberInput", description: "an input for entering Malta's Malta National Identification Number", status: "beta" },
  { name: "malta-national-identification-number-view", pascal: "MaltaNationalIdentificationNumberView", description: "a read-only display of Malta's Malta National Identification Number", status: "beta" },
  { name: "malta-passport-number-input", pascal: "MaltaPassportNumberInput", description: "an input for entering Malta's Malta Passport Number", status: "beta" },
  { name: "malta-passport-number-view", pascal: "MaltaPassportNumberView", description: "a read-only display of Malta's Malta Passport Number", status: "beta" },
  { name: "masonry", pascal: "Masonry", description: "a masonry layout container for variable-height items", status: "beta" },
  { name: "measurement-instance-input", pascal: "MeasurementInstanceInput", description: "an input for entering a measurement value and unit", status: "beta" },
  { name: "measurement-instance-view", pascal: "MeasurementInstanceView", description: "a read-only display of a measurement value and unit", status: "beta" },
  { name: "measurement-system-input", pascal: "MeasurementSystemInput", description: "an input for selecting a measurement system", status: "beta" },
  { name: "measurement-system-view", pascal: "MeasurementSystemView", description: "a read-only display of a measurement system", status: "beta" },
  { name: "measurement-unit-input", pascal: "MeasurementUnitInput", description: "an input for selecting a measurement unit", status: "beta" },
  { name: "measurement-unit-view", pascal: "MeasurementUnitView", description: "a read-only display of a measurement unit", status: "beta" },
  { name: "medical-banner", pascal: "MedicalBanner", description: "a prominent message bar across the top of a page, with medical information", status: "beta" },
  { name: "medical-banner-box", pascal: "MedicalBannerBox", description: "a medical banner box that is inside a medical-banner component, using flexbox horizontal, with medical information", status: "beta" },
  { name: "medical-banner-box-for-advice", pascal: "MedicalBannerBoxForAdvice", description: "a medical record banner box for advice information e.g. contacts, contexts, plans, etc.", status: "beta" },
  { name: "medical-banner-box-for-danger", pascal: "MedicalBannerBoxForDanger", description: "a medical record banner box for danger information e.g. reactions, warnings, alarms, etc.", status: "stable" },
  { name: "mentions-input", pascal: "MentionsInput", description: "a text input with at-mention autocomplete suggestions", status: "beta" },
  { name: "menu", pascal: "Menu", description: "a list of actions or options triggered by a button", status: "stable" },
  { name: "menu-bar", pascal: "MenuBar", description: "a horizontal bar of menu triggers", status: "stable" },
  { name: "menu-bar-button", pascal: "MenuBarButton", description: "one item in a menu bar", status: "stable" },
  { name: "menu-group", pascal: "MenuGroup", description: "a labeled section of menu items within a menu", status: "beta" },
  { name: "menu-item", pascal: "MenuItem", description: "one item in a menu", status: "stable" },
  { name: "meter", pascal: "Meter", description: "a gauge displaying a scalar value within a known range", status: "stable" },
  { name: "mockup-browser", pascal: "MockupBrowser", description: "a box area that looks like a web browser", status: "beta" },
  { name: "mockup-laptop", pascal: "MockupLaptop", description: "a box area that looks like a laptop computer", status: "beta" },
  { name: "mockup-phone-landscape", pascal: "MockupPhoneLandscape", description: "a box area that looks like a mobile phone in landscape orientation", status: "beta" },
  { name: "mockup-phone-portrait", pascal: "MockupPhonePortrait", description: "a box area that looks like a mobile phone", status: "beta" },
  { name: "mockup-shell", pascal: "MockupShell", description: "a box area that looks like a terminal shell", status: "beta" },
  { name: "mockup-tablet-landscape", pascal: "MockupTabletLandscape", description: "a box area that looks like a tablet computer in landscape mode", status: "beta" },
  { name: "mockup-tablet-portrait", pascal: "MockupTabletPortrait", description: "a box area that looks like a tablet computer in portrait mode", status: "beta" },
  { name: "mockup-watch", pascal: "MockupWatch", description: "a box area that looks like a smart watch", status: "beta" },
  { name: "mockup-window", pascal: "MockupWindow", description: "a box area that looks like a desktop window", status: "beta" },
  { name: "month-input", pascal: "MonthInput", description: "an input for selecting a month and year <input type=\"month\">", status: "beta" },
  { name: "mutually-exclusive", pascal: "MutuallyExclusive", description: "a container ensuring only one option can be selected from a group", status: "beta" },
  { name: "navigation-menu", pascal: "NavigationMenu", description: "a site-wide navigation menu with links", status: "stable" },
  { name: "nederland-burgerservice-nummer-input", pascal: "NederlandBurgerserviceNummerInput", description: "an input for entering Netherlands's Burgerservicenummer (BSN)", status: "beta" },
  { name: "nederland-burgerservice-nummer-view", pascal: "NederlandBurgerserviceNummerView", description: "a read-only display of Netherlands's Burgerservicenummer (BSN)", status: "beta" },
  { name: "nederland-identiteitskaart-nummer-input", pascal: "NederlandIdentiteitskaartNummerInput", description: "an input for entering Netherlands's Identiteitskaart Nummer", status: "beta" },
  { name: "nederland-identiteitskaart-nummer-view", pascal: "NederlandIdentiteitskaartNummerView", description: "a read-only display of Netherlands's Identiteitskaart Nummer", status: "beta" },
  { name: "nederland-paspoort-nummer-input", pascal: "NederlandPaspoortNummerInput", description: "an input for entering Netherlands's Paspoort Nummer", status: "beta" },
  { name: "nederland-paspoort-nummer-view", pascal: "NederlandPaspoortNummerView", description: "a read-only display of Netherlands's Paspoort Nummer", status: "beta" },
  { name: "net-promoter-score-picker", pascal: "NetPromoterScorePicker", description: "a picker for selecting a 0-10 Net Promoter Score", status: "stable" },
  { name: "net-promoter-score-picker-button", pascal: "NetPromoterScorePickerButton", description: "a picker button for selecting a 0-10 Net Promoter Score", status: "beta" },
  { name: "net-promoter-score-view", pascal: "NetPromoterScoreView", description: "a read-only display of a Net Promoter Score", status: "stable" },
  { name: "newsletter-signup", pascal: "NewsletterSignup", description: "an email subscription form composition with idle, submitting, success, and error states", status: "beta" },
  { name: "norge-fodselsnummer-input", pascal: "NorgeFodselsnummerInput", description: "an input for entering Norway's Fødselsnummer", status: "beta" },
  { name: "norge-fodselsnummer-view", pascal: "NorgeFodselsnummerView", description: "a read-only display of Norway's Fødselsnummer", status: "beta" },
  { name: "northern-ireland-health-and-care-number-input", pascal: "NorthernIrelandHealthAndCareNumberInput", description: "an input for entering Northern Ireland Health and Care (H&C) Number unique national healthcare identifier", status: "beta" },
  { name: "northern-ireland-health-and-care-number-view", pascal: "NorthernIrelandHealthAndCareNumberView", description: "a read-only display of Northern Ireland Health and Care (H&C) Number unique national healthcare identifier", status: "beta" },
  { name: "notification", pascal: "Notification", description: "a brief message about an event or update", status: "stable" },
  { name: "number-input", pascal: "NumberInput", description: "an input for entering a numeric value with validation <input type=\"number\">", status: "stable" },
  { name: "option", pascal: "Option", description: "an option element within a select dropdown", status: "stable" },
  { name: "organization", pascal: "Organization", description: "an organization component that contains other organization-related information", status: "beta" },
  { name: "overlay-container", pascal: "OverlayContainer", description: "a full-viewport overlay backdrop for modals and sheets", status: "beta" },
  { name: "padding-reset", pascal: "PaddingReset", description: "a container that resets padding inside fluid-width containers", status: "beta" },
  { name: "pagination-link", pascal: "PaginationLink", description: "one pagination link in the trail", status: "beta" },
  { name: "pagination-list", pascal: "PaginationList", description: "an ordered list of pagination list items", status: "stable" },
  { name: "pagination-list-item", pascal: "PaginationListItem", description: "one pagination list item in the trail", status: "stable" },
  { name: "pagination-nav", pascal: "PaginationNav", description: "an ordered list of page navigation links", status: "stable" },
  { name: "panel", pascal: "Panel", description: "a generic content panel with optional heading", status: "stable" },
  { name: "password-input", pascal: "PasswordInput", description: "an input for entering a password with obscured text <input type=\"password\">", status: "beta" },
  { name: "password-input-or-text-input-div", pascal: "PasswordInputOrTextInputDiv", description: "an input for entering a password <input type=\"password\"> or text <input type=\"text\"> with show/hide toggle", status: "beta" },
  { name: "person", pascal: "Person", description: "a person component that contains other person-related information", status: "beta" },
  { name: "phase-banner", pascal: "PhaseBanner", description: "a banner showing service development phase and inviting feedback", status: "beta" },
  { name: "photo-pack", pascal: "PhotoPack", description: "a collection of photos displayed together as a group", status: "beta" },
  { name: "pictogram", pascal: "Pictogram", description: "an icon-based component pairing an icon with a title and description in a centered or side layout", status: "beta" },
  { name: "pin-input-div", pascal: "PinInputDiv", description: "a series of single-digit inputs for entering a PIN or OTP code", status: "beta" },
  { name: "place", pascal: "Place", description: "a place component that contains other place-related information", status: "beta" },
  { name: "polska-numer-identyfikacji-podatkowej-input", pascal: "PolskaNumerIdentyfikacjiPodatkowejInput", description: "an input for entering Poland's Numer Identyfikacji Podatkowej (NIP)", status: "beta" },
  { name: "polska-numer-identyfikacji-podatkowej-view", pascal: "PolskaNumerIdentyfikacjiPodatkowejView", description: "a read-only display of Poland's Numer Identyfikacji Podatkowej (NIP)", status: "beta" },
  { name: "polska-pesel-input", pascal: "PolskaPeselInput", description: "an input for entering Poland's PESEL", status: "beta" },
  { name: "polska-pesel-view", pascal: "PolskaPeselView", description: "a read-only display of Poland's PESEL", status: "beta" },
  { name: "popconfirm-dialog", pascal: "PopconfirmDialog", description: "a popover dialog with confirm and cancel buttons", status: "beta" },
  { name: "popover", pascal: "Popover", description: "a floating content box anchored to a trigger element", status: "stable" },
  { name: "popup", pascal: "Popup", description: "a temporary overlay that appears above page content", status: "stable" },
  { name: "portugal-numero-de-identificacao-fiscal-input", pascal: "PortugalNumeroDeIdentificacaoFiscalInput", description: "an input for entering Portugal's Número de Identificação Fiscal (NIF)", status: "beta" },
  { name: "portugal-numero-de-identificacao-fiscal-view", pascal: "PortugalNumeroDeIdentificacaoFiscalView", description: "a read-only display of Portugal's Número de Identificação Fiscal (NIF)", status: "beta" },
  { name: "portugal-passaporte-input", pascal: "PortugalPassaporteInput", description: "an input for entering Portugal's Passaporte", status: "beta" },
  { name: "portugal-passaporte-view", pascal: "PortugalPassaporteView", description: "a read-only display of Portugal's Passaporte", status: "beta" },
  { name: "postal-code-input", pascal: "PostalCodeInput", description: "an input for entering a postal or ZIP code", status: "beta" },
  { name: "postal-code-view", pascal: "PostalCodeView", description: "a read-only display of a postal or ZIP code", status: "beta" },
  { name: "product-card", pascal: "ProductCard", description: "a specialized card for displaying a product with image, title, price, and actions", status: "beta" },
  { name: "progress", pascal: "Progress", description: "a horizontal progress bar showing completion", status: "stable" },
  { name: "progress-bar", pascal: "ProgressBar", description: "a horizontal progress indicator", status: "beta" },
  { name: "progress-circle", pascal: "ProgressCircle", description: "a circular progress indicator", status: "stable" },
  { name: "progress-spinner", pascal: "ProgressSpinner", description: "an indeterminate spinning progress indicator", status: "beta" },
  { name: "qr-code-image", pascal: "QrCodeImage", description: "a QR code image generated from text or URL data", status: "experimental" },
  { name: "question", pascal: "Question", description: "a question is anything that asks for information, invites a response, tests knowledge, etc.", status: "experimental" },
  { name: "radio-group", pascal: "RadioGroup", description: "a group of radio buttons for selecting one option", status: "stable" },
  { name: "radio-input", pascal: "RadioInput", description: "a single radio button input <input type=\"radio\">", status: "stable" },
  { name: "range-input", pascal: "RangeInput", description: "a slider input for selecting a value within a range <input type=\"range\">", status: "stable" },
  { name: "red-amber-green-picker", pascal: "RedAmberGreenPicker", description: "a picker for selecting a red/amber/green status", status: "stable" },
  { name: "red-amber-green-picker-button", pascal: "RedAmberGreenPickerButton", description: "a picker button for selecting a red/amber/green status", status: "beta" },
  { name: "red-amber-green-view", pascal: "RedAmberGreenView", description: "a read-only display of a red/amber/green status", status: "stable" },
  { name: "red-orange-yellow-green-blue-picker", pascal: "RedOrangeYellowGreenBluePicker", description: "a picker for selecting a five-level color status", status: "stable" },
  { name: "red-orange-yellow-green-blue-picker-button", pascal: "RedOrangeYellowGreenBluePickerButton", description: "a picker button for selecting a five-level color status", status: "beta" },
  { name: "red-orange-yellow-green-blue-view", pascal: "RedOrangeYellowGreenBlueView", description: "a read-only display of a five-level color status", status: "stable" },
  { name: "related-content", pascal: "RelatedContent", description: "a section providing links to related or supporting information", status: "beta" },
  { name: "reset-input", pascal: "ResetInput", description: "a button input that resets a form to default values <input type=\"reset\">", status: "stable" },
  { name: "resizable", pascal: "Resizable", description: "a container that the user can resize by dragging", status: "beta" },
  { name: "review-date", pascal: "ReviewDate", description: "a display of a content review date", status: "stable" },
  { name: "romania-cod-numeric-personal-input", pascal: "RomaniaCodNumericPersonalInput", description: "an input for entering Romania's Cod Numeric Personal (CNP)", status: "beta" },
  { name: "romania-cod-numeric-personal-view", pascal: "RomaniaCodNumericPersonalView", description: "a read-only display of Romania's Cod Numeric Personal (CNP)", status: "beta" },
  { name: "romania-pasaport-input", pascal: "RomaniaPasaportInput", description: "an input for entering Romania's Paşaport", status: "beta" },
  { name: "romania-pasaport-view", pascal: "RomaniaPasaportView", description: "a read-only display of Romania's Paşaport", status: "beta" },
  { name: "scatter-chart", pascal: "ScatterChart", description: "a scatter chart visualization using dots to display data", status: "beta" },
  { name: "screen-reader-span", pascal: "ScreenReaderSpan", description: "a visually hidden span of text intended for screen readers to provide more descriptive labels", status: "beta" },
  { name: "scroll-area", pascal: "ScrollArea", description: "a scrollable container with custom scrollbar support", status: "beta" },
  { name: "scroll-bar", pascal: "ScrollBar", description: "a custom scrollbar element", status: "beta" },
  { name: "scroller", pascal: "Scroller", description: "a scrollytelling container with step-based foreground and background composition", status: "beta" },
  { name: "scroller-base", pascal: "ScrollerBase", description: "a low-level scroll position tracking primitive for scrollytelling", status: "beta" },
  { name: "scroller-video", pascal: "ScrollerVideo", description: "a video-driven scrollytelling component with frame-by-frame scrubbing", status: "beta" },
  { name: "search-input", pascal: "SearchInput", description: "an input for entering a search query <input type=\"search\">", status: "stable" },
  { name: "section-heading", pascal: "SectionHeading", description: "a styled heading introducing a major content section, with optional eyebrow and subtitle", status: "beta" },
  { name: "section-link", pascal: "SectionLink", description: "one section link in the navigation", status: "beta" },
  { name: "section-list", pascal: "SectionList", description: "a list of section navigation items", status: "beta" },
  { name: "section-list-item", pascal: "SectionListItem", description: "one section navigation item", status: "beta" },
  { name: "section-nav", pascal: "SectionNav", description: "a navigation container for section navigation links", status: "beta" },
  { name: "segment-group", pascal: "SegmentGroup", description: "a group of mutually exclusive segment options", status: "stable" },
  { name: "segment-group-item", pascal: "SegmentGroupItem", description: "one selectable segment in a segment group", status: "stable" },
  { name: "select", pascal: "Select", description: "a dropdown select element for choosing one option", status: "stable" },
  { name: "select-with-extras", pascal: "SelectWithExtras", description: "a select dropdown with additional features like search or groups", status: "beta" },
  { name: "separator", pascal: "Separator", description: "a horizontal or vertical divider between content sections", status: "stable" },
  { name: "share-page", pascal: "SharePage", description: "a component for sharing the page on social media", status: "beta" },
  { name: "sheet", pascal: "Sheet", description: "a panel that slides in from a screen edge as an overlay", status: "stable" },
  { name: "sidebar", pascal: "Sidebar", description: "a side panel for navigation or supplementary content", status: "stable" },
  { name: "signature-pad", pascal: "SignaturePad", description: "a drawing area for capturing a handwritten signature", status: "beta" },
  { name: "skeleton", pascal: "Skeleton", description: "a placeholder loading animation for content", status: "stable" },
  { name: "skip-link", pascal: "SkipLink", description: "a hidden link for keyboard users to skip to main content", status: "stable" },
  { name: "slide-out-drawer", pascal: "SlideOutDrawer", description: "a drawer that slides out from the side of the page", status: "stable" },
  { name: "slider", pascal: "Slider", description: "a draggable control for selecting a value along a track", status: "stable" },
  { name: "slider-button", pascal: "SliderButton", description: "a button with a slider that the user needs to slide to confirm", status: "beta" },
  { name: "slovenija-emso-input", pascal: "SlovenijaEmsoInput", description: "an input for entering Slovenia's Enotna Matična Številka Občana (EMŠO)", status: "beta" },
  { name: "slovenija-emso-view", pascal: "SlovenijaEmsoView", description: "a read-only display of Slovenia's Enotna Matična Številka Občana (EMŠO)", status: "beta" },
  { name: "slovensko-pas-input", pascal: "SlovenskoPasInput", description: "an input for entering Slovakia's Pas", status: "beta" },
  { name: "slovensko-pas-view", pascal: "SlovenskoPasView", description: "a read-only display of Slovakia's Pas", status: "beta" },
  { name: "slovensko-rodne-cislo-input", pascal: "SlovenskoRodneCisloInput", description: "an input for entering Slovakia's Rodné číslo (RČ)", status: "beta" },
  { name: "slovensko-rodne-cislo-view", pascal: "SlovenskoRodneCisloView", description: "a read-only display of Slovakia's Rodné číslo (RČ)", status: "beta" },
  { name: "sonner", pascal: "Sonner", description: "a toast notification manager", status: "beta" },
  { name: "sparkline", pascal: "Sparkline", description: "a small inline chart showing a data trend", status: "stable" },
  { name: "split-button", pascal: "SplitButton", description: "a button with a primary action and a dropdown for related actions", status: "beta" },
  { name: "split-view", pascal: "SplitView", description: "a two-panel resizable layout container with a draggable divider between them", status: "beta" },
  { name: "splitter", pascal: "Splitter", description: "a draggable divider for resizing adjacent panels", status: "beta" },
  { name: "statistic", pascal: "Statistic", description: "a numeric value display with title, prefix, and suffix", status: "beta" },
  { name: "status-light", pascal: "StatusLight", description: "a small colored dot status indicator paired with a status label", status: "beta" },
  { name: "status-tag", pascal: "StatusTag", description: "a tag showing the current status of a task", status: "beta" },
  { name: "step-list", pascal: "StepList", description: "an ordered list of step items showing progress through a multi-step process", status: "beta" },
  { name: "step-list-item", pascal: "StepListItem", description: "one step in a step list with status of waiting, in progress, finished, or error", status: "beta" },
  { name: "sticky-promo-banner", pascal: "StickyPromoBanner", description: "a fixed-position promotional banner with a dismiss button", status: "beta" },
  { name: "submit-input", pascal: "SubmitInput", description: "a button input that submits a form <input type=\"submit\">", status: "stable" },
  { name: "success-panel", pascal: "SuccessPanel", description: "a panel confirming a task has been completed", status: "beta" },
  { name: "summary-box", pascal: "SummaryBox", description: "a boxed callout highlighting key takeaways or next steps from a longer page", status: "beta" },
  { name: "summary-list", pascal: "SummaryList", description: "an ordered list of key-value summary pairs", status: "stable" },
  { name: "summary-list-item", pascal: "SummaryListItem", description: "one key-value pair in a summary list", status: "stable" },
  { name: "suomi-henkilotunnus-input", pascal: "SuomiHenkilotunnusInput", description: "an input for entering Finland's Henkilötunnus (HETU)", status: "beta" },
  { name: "suomi-henkilotunnus-view", pascal: "SuomiHenkilotunnusView", description: "a read-only display of Finland's Henkilötunnus (HETU)", status: "beta" },
  { name: "super-banner", pascal: "SuperBanner", description: "a super-banner communicates a high-priority state that affects an entire app, experience, process, or system", status: "beta" },
  { name: "sverige-personnummer-input", pascal: "SverigePersonnummerInput", description: "an input for entering Sweden's Personnummer", status: "beta" },
  { name: "sverige-personnummer-view", pascal: "SverigePersonnummerView", description: "a read-only display of Sweden's Personnummer", status: "beta" },
  { name: "switch-button", pascal: "SwitchButton", description: "a toggle switch for turning a setting on or off", status: "stable" },
  { name: "tab-bar", pascal: "TabBar", description: "a group of tabs for switching between content panels", status: "stable" },
  { name: "tab-bar-button", pascal: "TabBarButton", description: "one tab button in a tab group", status: "stable" },
  { name: "tab-panel", pascal: "TabPanel", description: "a content panel associated with a tab in a tab bar", status: "beta" },
  { name: "table", pascal: "Table", description: "a table with rows and columns <table>", status: "beta" },
  { name: "table-body", pascal: "TableBody", description: "a table interactive grid tbody <tbody>", status: "beta" },
  { name: "table-foot", pascal: "TableFoot", description: "a table interactive grid tfoot <tfoot>", status: "beta" },
  { name: "table-head", pascal: "TableHead", description: "a table interactive grid thead <thead>", status: "beta" },
  { name: "table-row", pascal: "TableRow", description: "a table interactive grid row <tr>", status: "beta" },
  { name: "table-td", pascal: "TableTD", description: "a table interactive grid data cell <td>", status: "beta" },
  { name: "table-th", pascal: "TableTH", description: "a table interactive grid header cell <th>", status: "beta" },
  { name: "tag", pascal: "Tag", description: "a keyword label for categorizing content", status: "stable" },
  { name: "tag-group", pascal: "TagGroup", description: "a group of tag elements", status: "stable" },
  { name: "tag-input", pascal: "TagInput", description: "an input for adding and removing tags", status: "stable" },
  { name: "task-bar", pascal: "TaskBar", description: "a horizontal bar of task shortcuts or actions", status: "beta" },
  { name: "task-bar-button", pascal: "TaskBarButton", description: "one item in a task bar", status: "beta" },
  { name: "task-list", pascal: "TaskList", description: "an ordered list of task list items", status: "stable" },
  { name: "task-list-item", pascal: "TaskListItem", description: "one task item with a checkbox and label", status: "stable" },
  { name: "tel-input", pascal: "TelInput", description: "an input for entering a telephone number <input type=\"tel\">", status: "stable" },
  { name: "tel-link", pascal: "TelLink", description: "a tel hyperlink for a telephone number", status: "beta" },
  { name: "text-area-input", pascal: "TextAreaInput", description: "a multi-line text input area", status: "stable" },
  { name: "text-area-input-with-character-counter", pascal: "TextAreaInputWithCharacterCounter", description: "a multi-line text area input with a caption below that is a character counter \"[number] of [maximum] characters\"", status: "beta" },
  { name: "text-input", pascal: "TextInput", description: "a single-line text input field <input type=\"text\">", status: "stable" },
  { name: "text-input-with-search", pascal: "TextInputWithSearch", description: "a single-line text input field <input type=\"text\"> with search capability", status: "beta" },
  { name: "theme-provider", pascal: "ThemeProvider", description: "a container that applies CSS custom properties from a theme object to its children", status: "beta" },
  { name: "theme-select", pascal: "ThemeSelect", description: "a select dropdown for choosing a theme", status: "stable" },
  { name: "theme-select-option", pascal: "ThemeSelectOption", description: "one option in a theme select dropdown", status: "stable" },
  { name: "theme-view", pascal: "ThemeView", description: "a read-only display of the current theme", status: "stable" },
  { name: "tile", pascal: "Tile", description: "a grouping container that presents related content in a structured format, often as a single clickable area", status: "beta" },
  { name: "tile-map", pascal: "TileMap", description: "a tile cartogram map with configurable layers for geographic data visualization", status: "beta" },
  { name: "time-input", pascal: "TimeInput", description: "an input for entering a time value <input type=\"time\">", status: "stable" },
  { name: "time-picker-input", pascal: "TimePickerInput", description: "an input with a dropdown for picking a time", status: "beta" },
  { name: "timeline-list", pascal: "TimelineList", description: "an ordered list of chronological events or milestones", status: "stable" },
  { name: "timeline-list-item", pascal: "TimelineListItem", description: "one event in a timeline list", status: "stable" },
  { name: "timeout-dialog", pascal: "TimeoutDialog", description: "a modal dialog warning users before session timeout", status: "beta" },
  { name: "timer", pascal: "Timer", description: "a countdown or elapsed time display", status: "stable" },
  { name: "timer-button", pascal: "TimerButton", description: "a button with a timer that will automatically click after a given amount of time", status: "beta" },
  { name: "toast", pascal: "Toast", description: "a brief auto-dismissing notification message", status: "beta" },
  { name: "toggle-button", pascal: "ToggleButton", description: "a button that toggles between pressed and unpressed states", status: "stable" },
  { name: "toggle-group", pascal: "ToggleGroup", description: "a group of toggle buttons for selecting options", status: "stable" },
  { name: "tool-bar", pascal: "ToolBar", description: "a horizontal bar of tool actions", status: "stable" },
  { name: "tool-bar-button", pascal: "ToolBarButton", description: "one action button in a tool bar", status: "stable" },
  { name: "tooltip", pascal: "Tooltip", description: "a small popup showing descriptive text on hover or focus", status: "stable" },
  { name: "tour", pascal: "Tour", description: "a tour guide, such as for sightseeing, or pathways, or demonstrations, etc.", status: "stable" },
  { name: "tour-list", pascal: "TourList", description: "an ordered list of tour guide steps", status: "stable" },
  { name: "tour-list-item", pascal: "TourListItem", description: "one step in a tour guide list", status: "stable" },
  { name: "transfer-list", pascal: "TransferList", description: "a dual list box for moving items between two lists", status: "beta" },
  { name: "tree-link", pascal: "TreeLink", description: "one link in the tree", status: "beta" },
  { name: "tree-list", pascal: "TreeList", description: "a hierarchical list with nested expandable items", status: "stable" },
  { name: "tree-list-item", pascal: "TreeListItem", description: "one item in a tree navigation list", status: "beta" },
  { name: "tree-menu", pascal: "TreeMenu", description: "a hierarchical tree menu with expandable branches", status: "beta" },
  { name: "tree-nav", pascal: "TreeNav", description: "a hierarchical navigation with expandable branches", status: "stable" },
  { name: "tree-select", pascal: "TreeSelect", description: "a select dropdown showing a tree of hierarchical options", status: "beta" },
  { name: "united-kingdom-national-health-service-number-input", pascal: "UnitedKingdomNationalHealthServiceNumberInput", description: "an input for entering a UK NHS number", status: "beta" },
  { name: "united-kingdom-national-health-service-number-view", pascal: "UnitedKingdomNationalHealthServiceNumberView", description: "a read-only display of a UK NHS number", status: "beta" },
  { name: "united-kingdom-national-insurance-number-input", pascal: "UnitedKingdomNationalInsuranceNumberInput", description: "an input for entering United Kingdom's National Insurance Number (NINO)", status: "beta" },
  { name: "united-kingdom-national-insurance-number-view", pascal: "UnitedKingdomNationalInsuranceNumberView", description: "a read-only display of United Kingdom's National Insurance Number (NINO)", status: "beta" },
  { name: "united-states-social-security-number-input", pascal: "UnitedStatesSocialSecurityNumberInput", description: "an input for entering a US Social Security number", status: "beta" },
  { name: "united-states-social-security-number-view", pascal: "UnitedStatesSocialSecurityNumberView", description: "a read-only display of a US Social Security number", status: "beta" },
  { name: "url-input", pascal: "UrlInput", description: "an input for entering a URL <input type=\"url\">", status: "beta" },
  { name: "validation-list", pascal: "ValidationList", description: "a live-feedback list of input validation rules with pending, passed, and failed states", status: "beta" },
  { name: "validation-list-item", pascal: "ValidationListItem", description: "one validation rule in a validation list with a status of pending, passed, or failed", status: "beta" },
  { name: "video-player", pascal: "VideoPlayer", description: "a video player with play-in-view behavior, custom controls, and IntersectionObserver support", status: "beta" },
  { name: "visible", pascal: "Visible", description: "an IntersectionObserver wrapper that exposes element visibility state", status: "beta" },
  { name: "warning-callout", pascal: "WarningCallout", description: "a callout box highlighting a warning message", status: "stable" },
  { name: "watermark", pascal: "Watermark", description: "a decorative repeating overlay text or image marking a page", status: "beta" },
  { name: "week-input", pascal: "WeekInput", description: "an input for selecting a week and year <input type=\"week\">", status: "beta" },
];
