<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once ToolCallStatus's real design lands.
  const demoHtml: string = `<div class="tool-call-status" aria-label="the status of a tool call as a word, such as pending, running, done or error">ToolCallStatus</div>`;
</script>

<svelte:head>
  <title>ToolCallStatus — Lily Design System</title>
  <meta name="description" content="the status of a tool call as a word, such as pending, running, done or error" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>ToolCallStatus</h1>
  <p>the status of a tool call as a word, such as pending, running, done or error</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/tool-call-status/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: tool-call-status</li>
      <li>PascalCase: ToolCallStatus</li>
      <li>Description: the status of a tool call as a word, such as pending, running, done or error</li>
      <li>Status: beta — implemented and unit-tested in all eight headless libraries; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;span&gt;</li>
      <li>CSS class: .tool-call-status</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li>No role: the status is plain text so it is read in order</li>
      <li><code>data-status</code> is for consumer CSS only</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>None</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>class</code>: string -- Appended to the base class</li>
      <li><code>status</code>: string (optional) -- <code>pending</code>, <code>running</code>, <code>done</code> or <code>error</code>; sets <code>data-status</code></li>
      <li><code>children</code>: slot -- The visible status word</li>
      <li><code>...restProps</code>: HTML attributes -- Spread onto the root <code>&lt;span&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
