<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once OneTimePasswordInput's real design lands.
  const demoHtml: string = `<div class="one-time-password-input" aria-label="a single one-time-password input with a numeric keypad, SMS autofill, and a fixed length">OneTimePasswordInput</div>`;
</script>

<svelte:head>
  <title>OneTimePasswordInput — Lily Design System</title>
  <meta name="description" content="a single one-time-password input with a numeric keypad, SMS autofill, and a fixed length" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>OneTimePasswordInput</h1>
  <p>a single one-time-password input with a numeric keypad, SMS autofill, and a fixed length</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/one-time-password-input/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: one-time-password-input</li>
      <li>PascalCase: OneTimePasswordInput</li>
      <li>Description: a single one-time-password input with a numeric keypad, SMS autofill, and a fixed length</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;input&gt;</li>
      <li>CSS class: .one-time-password-input</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>aria-label=&#123;label&#125;</code> -- provides the accessible name when no visible <code>&lt;label&gt;</code> is associated</li>
      <li><code>autocomplete="one-time-code"</code> -- WCAG 1.3.5 input purpose, lets the platform offer the received code</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>None beyond native input behaviour -- standard text editing keys; Tab moves focus in and out</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class name appended to the base class</li>
      <li><code>label</code>: string (required) -- accessible name via <code>aria-label</code></li>
      <li><code>length</code>: number (required) -- number of characters in the code; sets <code>maxlength</code> and <code>data-length</code></li>
      <li><code>value</code>: string (default: <code>""</code>) -- bindable value</li>
      <li><code>inputMode</code>: string (default: <code>"numeric"</code>) -- virtual keyboard hint; use <code>"text"</code> for alphanumeric codes</li>
      <li><code>pattern</code>: string (default: <code>"[0-9]*"</code>) -- allowed characters</li>
      <li><code>name</code>: string (optional) -- form field name</li>
      <li><code>required</code>: boolean (default: <code>false</code>)</li>
      <li><code>disabled</code>: boolean (default: <code>false</code>)</li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the <code>&lt;input&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
