<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once ToolCall's real design lands.
  const demoHtml: string = `<div class="tool-call" aria-label="a collapsible record of one tool invocation by an AI agent, with a name, a status word, and its input, output or error">ToolCall</div>`;
</script>

<svelte:head>
  <title>ToolCall — Lily Design System</title>
  <meta name="description" content="a collapsible record of one tool invocation by an AI agent, with a name, a status word, and its input, output or error" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>ToolCall</h1>
  <p>a collapsible record of one tool invocation by an AI agent, with a name, a status word, and its input, output or error</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/tool-call/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: tool-call</li>
      <li>PascalCase: ToolCall</li>
      <li>Description: a collapsible record of one tool invocation by an AI agent, with a name, a status word, and its input, output or error</li>
      <li>Status: beta — implemented and unit-tested in all eight headless libraries; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;details&gt;</li>
      <li>CSS class: .tool-call</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li>Native <code>&lt;details&gt;</code>/<code>&lt;summary&gt;</code> semantics; no ARIA role is added</li>
      <li><code>aria-busy="true"</code> only while <code>status="running"</code></li>
      <li><code>data-status</code> is for consumer CSS; the visible status word (in <code>ToolCallStatus</code>) carries the meaning, never colour alone</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Enter / Space on the native <code>&lt;summary&gt;</code> toggles</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>class</code>: string -- Appended to the base class</li>
      <li><code>status</code>: string (optional) -- <code>pending</code>, <code>running</code>, <code>done</code> or <code>error</code>; sets <code>data-status</code>, and <code>aria-busy="true"</code> only while running</li>
      <li><code>open</code>: boolean -- Whether expanded (bindable / <code>v-model</code> / <code>@bind-Open</code> / <code>open</code> attribute)</li>
      <li><code>summary</code>: slot -- Summary content: name and status words</li>
      <li><code>children</code>: slot -- The body</li>
      <li><code>...restProps</code>: HTML attributes -- Spread onto the root <code>&lt;details&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
