<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once ToolCallError's real design lands.
  const demoHtml: string = `<div class="tool-call-error" aria-label="the error shown when a tool call fails">ToolCallError</div>`;
</script>

<svelte:head>
  <title>ToolCallError — Lily Design System</title>
  <meta name="description" content="the error shown when a tool call fails" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>ToolCallError</h1>
  <p>the error shown when a tool call fails</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/tool-call-error/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: tool-call-error</li>
      <li>PascalCase: ToolCallError</li>
      <li>Description: the error shown when a tool call fails</li>
      <li>Status: beta — implemented and unit-tested in all eight headless libraries; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;div&gt;</li>
      <li>CSS class: .tool-call-error</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>role="alert"</code> announces the error when it is added</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>None</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>class</code>: string -- Appended to the base class</li>
      <li><code>children</code>: slot -- The error message</li>
      <li><code>...restProps</code>: HTML attributes -- Spread onto the root <code>&lt;div&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
