<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once CalendarYearTable's real design lands.
  const demoHtml: string = `<div class="calendar-year-table" aria-label="a calendar grid showing the twelve months of one year">CalendarYearTable</div>`;
</script>

<svelte:head>
  <title>CalendarYearTable — Lily Design System</title>
  <meta name="description" content="a calendar grid showing the twelve months of one year" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>CalendarYearTable</h1>
  <p>a calendar grid showing the twelve months of one year</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/calendar-year-table/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: calendar-year-table</li>
      <li>PascalCase: CalendarYearTable</li>
      <li>Description: a calendar grid showing the twelve months of one year (typically 3 x 4 or 4 x 3 month cells)</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;table&gt;</li>
      <li>CSS class: .calendar-year-table</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>role="grid"</code> -- identifies the table as an interactive grid widget</li>
      <li><code>aria-label=&#123;label&#125;</code> -- provides an accessible name describing the period</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>No keyboard interactions built in — the consumer implements grid navigation</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>class</code>: string (default: <code>""</code>) -- appended to the base class</li>
      <li><code>label</code>: string (required) -- accessible name describing the period shown, applied via <code>aria-label</code></li>
      <li><code>caption</code>: string (optional) -- visible caption</li>
      <li><code>children</code>: slot (required) -- table sections and rows</li>
      <li><code>...restProps</code>: HTML attributes -- spread onto the root <code>&lt;table&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
