<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once EmptyState's real design lands.
  const demoHtml: string = `<div class="empty-state" aria-label="a placeholder shown when a list, table, or view has nothing to display yet, with room for guidance and an action">EmptyState</div>`;
</script>

<svelte:head>
  <title>EmptyState — Lily Design System</title>
  <meta name="description" content="a placeholder shown when a list, table, or view has nothing to display yet, with room for guidance and an action" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>EmptyState</h1>
  <p>a placeholder shown when a list, table, or view has nothing to display yet, with room for guidance and an action</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/empty-state/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: empty-state</li>
      <li>PascalCase: EmptyState</li>
      <li>Description: a container for the nothing-here-yet state of a list, table, search or inbox</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;div&gt;</li>
      <li>CSS class: .empty-state</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>role="group"</code> and <code>aria-label=&#123;label&#125;</code> -- only when <code>label</code> is provided</li>
      <li>No <code>aria-live</code>: use <code>info-state</code> (<code>role="status"</code>) when the state must be announced</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>None. Any action inside is a native control with its own keyboard behaviour</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class name appended to the base class</li>
      <li><code>label</code>: string (optional) -- accessible name; adds <code>role="group"</code></li>
      <li><code>children</code>: slot -- heading, text and action supplied by the consumer</li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the root</li>
    </ul>
</section>
<!-- END generated: canonical contract -->
