// Generated by bin/generate-site-pages — do not edit; regenerate with the script.
import { test, expect } from '@playwright/test';

const slug = 'nederland-paspoort-nummer-input';
const title = "NederlandPaspoortNummerInput";

test.describe('component page: ' + slug, () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/components/' + slug + '/');
  });

  test('responds with a non-error status', async ({ page }) => {
    const res = await page.goto('/components/' + slug + '/');
    expect(res, 'navigation response').not.toBeNull();
    expect(res!.status(), 'http status').toBeLessThan(400);
  });

  test('document title contains the component name', async ({ page }) => {
    // Pages carry the name either as PascalCase or as the docs' spaced title; ignore spaces and case.
    const normalised = (await page.title()).replace(/\s+/g, '').toLowerCase();
    expect(normalised).toContain(title.toLowerCase() + '—lilydesignsystem');
  });

  test('renders the H1 heading', async ({ page }) => {
    // The heading is the docs' own title ("Date Range"); match the component name ignoring spaces and case.
    const h1 = page.getByRole('heading', { level: 1 }).first();
    await expect(h1).toBeVisible();
    const text = ((await h1.textContent()) || '').replace(/\s+/g, '').toLowerCase();
    expect(text).toContain(title.toLowerCase());
  });

  test('shows the breadcrumb back-link to /components/', async ({ page }) => {
    const back = page.getByRole('link', { name: /All components/ });
    await expect(back).toBeVisible();
    await expect(back).toHaveAttribute('href', '/components/');
  });

  test('renders the documentation article', async ({ page }) => {
    await expect(page.locator('article.component-page')).toBeVisible();
  });
});
