<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once ShowMore's real design lands.
  const demoHtml: string = `<div class="show-more" aria-label="a content region clamped to a shorter height with a button that reveals the rest">ShowMore</div>`;
</script>

<svelte:head>
  <title>ShowMore — Lily Design System</title>
  <meta name="description" content="a content region clamped to a shorter height with a button that reveals the rest" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>ShowMore</h1>
  <p>a content region clamped to a shorter height with a button that reveals the rest</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/show-more/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: show-more</li>
      <li>PascalCase: ShowMore</li>
      <li>Description: clamp long content behind a show more / show less toggle</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;div&gt;</li>
      <li>CSS class: .show-more</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>aria-expanded=&#123;expanded&#125;</code> -- on the button</li>
      <li><code>aria-controls=&#123;contentId&#125;</code> -- on the button, references the content <code>id</code></li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Enter: toggles when the button has focus (native)</li>
      <li>Space: toggles when the button has focus (native)</li>
      <li>Tab: moves focus to / from the button</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class name appended to the base class</li>
      <li><code>moreLabel</code>: string (required) -- button text while collapsed</li>
      <li><code>lessLabel</code>: string (required) -- button text while expanded</li>
      <li><code>expanded</code>: boolean (default: <code>false</code>) -- bindable</li>
      <li><code>children</code>: slot -- the content</li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the root</li>
    </ul>
</section>
<!-- END generated: canonical contract -->
