<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once MultiSelect's real design lands.
  const demoHtml: string = `<div class="multi-select" aria-label="a native select that allows choosing several options at once">MultiSelect</div>`;
</script>

<svelte:head>
  <title>MultiSelect — Lily Design System</title>
  <meta name="description" content="a native select that allows choosing several options at once" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>MultiSelect</h1>
  <p>a native select that allows choosing several options at once</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/multi-select/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: multi-select</li>
      <li>PascalCase: MultiSelect</li>
      <li>Description: a native select that lets the user choose several options at once</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;select&gt;</li>
      <li>CSS class: .multi-select</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>aria-label=&#123;label&#125;</code> -- accessible name; the <code>&lt;select multiple&gt;</code> is exposed as a listbox with multiple selection</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Arrow Up / Arrow Down: moves the active option (native); Shift+Arrow extends the selection (native)</li>
      <li>Ctrl/Cmd+Click and Ctrl/Cmd+Space: toggle one option (native, platform-dependent)</li>
      <li>Native only: no keyboard handling is added</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class name appended to the base class</li>
      <li><code>label</code>: string (required) -- accessible name via <code>aria-label</code></li>
      <li><code>value</code>: string[] (default: <code>[]</code>) -- bindable selected values</li>
      <li><code>size</code>: number (optional) -- visible rows</li>
      <li><code>required</code>: boolean (default: <code>false</code>)</li>
      <li><code>disabled</code>: boolean (default: <code>false</code>)</li>
      <li><code>children</code>: slot (required) -- <code>Option</code> elements</li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the <code>&lt;select&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
