<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once StreamingText's real design lands.
  const demoHtml: string = `<div class="streaming-text" aria-label="text that arrives in chunks, as an AI answer streams in, announced once to screen readers when complete">StreamingText</div>`;
</script>

<svelte:head>
  <title>StreamingText — Lily Design System</title>
  <meta name="description" content="text that arrives in chunks, as an AI answer streams in, announced once to screen readers when complete" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>StreamingText</h1>
  <p>text that arrives in chunks, as an AI answer streams in, announced once to screen readers when complete</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/streaming-text/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: streaming-text</li>
      <li>PascalCase: StreamingText</li>
      <li>Description: text that arrives in chunks, as an AI answer streams in, announced once to screen readers when complete</li>
      <li>Status: beta — implemented and unit-tested in all eight headless libraries; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;div&gt;</li>
      <li>CSS class: .streaming-text</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>role="status"</code>, <code>aria-live="polite"</code>, <code>aria-atomic="true"</code></li>
      <li><code>aria-busy="true"</code> while streaming</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>No keyboard interactions</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>class</code>: string (default: <code>""</code>) -- appended to the base class</li>
      <li><code>label</code>: string (optional) -- accessible name</li>
      <li><code>streaming</code>: boolean (default: <code>false</code>) -- true while chunks are still arriving</li>
      <li><code>children</code>: slot -- the text so far</li>
      <li><code>...restProps</code>: HTML attributes -- spread onto the root <code>&lt;div&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
