<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once FileTree's real design lands.
  const demoHtml: string = `<div class="file-tree" aria-label="a hierarchical tree of folders and files with expandable folders">FileTree</div>`;
</script>

<svelte:head>
  <title>FileTree — Lily Design System</title>
  <meta name="description" content="a hierarchical tree of folders and files with expandable folders" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>FileTree</h1>
  <p>a hierarchical tree of folders and files with expandable folders</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/file-tree/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: file-tree</li>
      <li>PascalCase: FileTree</li>
      <li>Description: a hierarchical tree of folders and files with expandable folders</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;ul&gt;</li>
      <li>CSS class: .file-tree</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>role="tree"</code> and <code>aria-label=&#123;label&#125;</code> on the root</li>
      <li>Consumer supplies <code>role="treeitem"</code>, <code>role="group"</code>, <code>aria-expanded</code> (folders) and <code>aria-selected</code></li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Tab: moves focus into the tree to the single tab-stop item, and out of it</li>
      <li>ArrowDown / ArrowUp: next / previous visible item (no wrap)</li>
      <li>ArrowRight: on a closed folder opens it; on an open folder moves to its first child</li>
      <li>ArrowLeft: on an open folder closes it; otherwise moves to the parent folder</li>
      <li>Home / End: first / last visible item</li>
      <li><code>*</code>: expands all closed sibling folders at the focused level</li>
      <li>Printable characters: typeahead to the next visible item whose text starts with the typed characters</li>
      <li>Enter / Space: activates the focused item</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class name appended to the base class</li>
      <li><code>label</code>: string (required) -- accessible name via <code>aria-label</code></li>
      <li><code>children</code>: slot -- the tree items</li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the <code>&lt;ul&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
