<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once ZhongguoJuminShenfenzhengHaomaView's real design lands.
  const demoHtml: string = `<div class="zhongguo-jumin-shenfenzheng-haoma-view" aria-label="a read-only display of China's Resident Identity Card Number">ZhongguoJuminShenfenzhengHaomaView</div>`;
</script>

<svelte:head>
  <title>ZhongguoJuminShenfenzhengHaomaView — Lily Design System</title>
  <meta name="description" content="a read-only display of China's Resident Identity Card Number" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>ZhongguoJuminShenfenzhengHaomaView</h1>
  <p>a read-only display of China's Resident Identity Card Number</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/zhongguo-jumin-shenfenzheng-haoma-view/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: zhongguo-jumin-shenfenzheng-haoma-view</li>
      <li>PascalCase: ZhongguoJuminShenfenzhengHaomaView</li>
      <li>Description: a read-only display of China's 居民身份证号码 (Jūmín Shēnfènzhèng Hàomǎ)</li>
      <li>Status: beta — implemented and unit-tested in all seven frameworks; not yet exercised in a composed flow</li>
      <li>HTML tag: &lt;span&gt;</li>
      <li>CSS class: .zhongguo-jumin-shenfenzheng-haoma-view</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>aria-label</code> provides accessible name from label prop</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Not interactive</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>value</code>: string (default: "") — the identifier to display</li>
      <li><code>label</code>: string (required) — accessible name via <code>aria-label</code></li>
      <li><code>...restProps</code>: any additional HTML attributes spread onto the root</li>
    </ul>
</section>
<!-- END generated: canonical contract -->
