<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once KbdShortcut's real design lands.
  const demoHtml: string = `<div class="kbd-shortcut" aria-label="a keyboard shortcut made of one or more key caps, for example Ctrl plus K">KbdShortcut</div>`;
</script>

<svelte:head>
  <title>KbdShortcut — Lily Design System</title>
  <meta name="description" content="a keyboard shortcut made of one or more key caps, for example Ctrl plus K" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>KbdShortcut</h1>
  <p>a keyboard shortcut made of one or more key caps, for example Ctrl plus K</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/kbd-shortcut/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: kbd-shortcut</li>
      <li>PascalCase: KbdShortcut</li>
      <li>Description: a multi-key keyboard shortcut shown as a row of key caps</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;kbd&gt;</li>
      <li>CSS class: .kbd-shortcut</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li>Separators are <code>aria-hidden="true"</code> so they are not read</li>
      <li><code>aria-label=&#123;label&#125;</code> -- optional spoken form on the root</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>None. KbdShortcut is a passive display element</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class name appended to the base class</li>
      <li><code>keys</code>: string[] (required) -- the key names, in order</li>
      <li><code>separator</code>: string (default: <code>"+"</code>) -- decorative separator between keys</li>
      <li><code>label</code>: string (optional) -- spoken form, applied as <code>aria-label</code></li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the root</li>
    </ul>
</section>
<!-- END generated: canonical contract -->
