<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once Mark's real design lands.
  const demoHtml: string = `<div class="mark" aria-label="an inline highlight marking text as relevant or referenced, such as a search match, using the native mark element">Mark</div>`;
</script>

<svelte:head>
  <title>Mark — Lily Design System</title>
  <meta name="description" content="an inline highlight marking text as relevant or referenced, such as a search match, using the native mark element" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>Mark</h1>
  <p>an inline highlight marking text as relevant or referenced, such as a search match, using the native mark element</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/mark/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: mark</li>
      <li>PascalCase: Mark</li>
      <li>Description: an inline highlight marking text as relevant or referenced, such as a search match, using the native mark element</li>
      <li>Status: beta — implemented and unit-tested in all eight headless libraries; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;mark&gt;</li>
      <li>CSS class: .mark</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li>None added; native <code>&lt;mark&gt;</code> semantics</li>
      <li>Consumers may pass <code>aria-label</code> / <code>aria-roledescription</code> through rest props for a spoken cue</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>None</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>class</code>: string (default: <code>""</code>) -- appended to the base class</li>
      <li><code>children</code>: slot -- the highlighted text</li>
      <li><code>...restProps</code>: HTML attributes -- spread onto the root <code>&lt;mark&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
