<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once ToolCallInput's real design lands.
  const demoHtml: string = `<div class="tool-call-input" aria-label="the input or arguments passed to a tool in a tool call">ToolCallInput</div>`;
</script>

<svelte:head>
  <title>ToolCallInput — Lily Design System</title>
  <meta name="description" content="the input or arguments passed to a tool in a tool call" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>ToolCallInput</h1>
  <p>the input or arguments passed to a tool in a tool call</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/tool-call-input/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: tool-call-input</li>
      <li>PascalCase: ToolCallInput</li>
      <li>Description: the input or arguments passed to a tool in a tool call</li>
      <li>Status: beta — implemented and unit-tested in all eight headless libraries; not yet exercised in composed flows</li>
      <li>HTML tag: &lt;div&gt;</li>
      <li>CSS class: .tool-call-input</li>
      <li>Interactive: no</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li><code>role="group"</code> with <code>aria-label</code> only when <code>label</code> is given</li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>None. If a long <code>&lt;pre&gt;</code> inside scrolls, give it <code>tabindex="0"</code> so keyboard users can scroll it</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>class</code>: string -- Appended to the base class</li>
      <li><code>label</code>: string (optional) -- Adds <code>role="group"</code> and <code>aria-label</code>; without it neither is rendered</li>
      <li><code>children</code>: slot -- The arguments</li>
      <li><code>...restProps</code>: HTML attributes -- Spread onto the root <code>&lt;div&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
