<script lang="ts">
  // Generated by bin/new-component (plan P7-T3). This is a simplified
  // placeholder route -- the other 490 component pages are rendered
  // from a fuller markdown-to-HTML pipeline; replace this page's body
  // with real content once Thinking's real design lands.
  const demoHtml: string = `<div class="thinking" aria-label="a collapsible block that shows an AI agent's reasoning or thinking, closed by default">Thinking</div>`;
</script>

<svelte:head>
  <title>Thinking — Lily Design System</title>
  <meta name="description" content="a collapsible block that shows an AI agent's reasoning or thinking, closed by default" />
</svelte:head>

<nav class="component-page-back" aria-label="Breadcrumb" style="max-width: 64rem; margin: 0 auto; padding: 1.5rem 1rem 0;">
  <a href="/components/">← All components</a>
</nav>

<article class="component-page prose" style="max-width: 64rem; margin: 0 auto; padding: 1rem 1rem 2rem;">
  <h1>Thinking</h1>
  <p>a collapsible block that shows an AI agent's reasoning or thinking, closed by default</p>
  <p><em>Status: experimental — generated by bin/new-component; not yet reviewed.</em></p>
  <h2>Demo</h2>
  {@html demoHtml}
</article>

<!-- BEGIN generated: canonical contract (bin/generate-api-docs) -->
<section class="component-contract prose" aria-labelledby="contract-heading" style="max-width: 64rem; margin: 0 auto; padding: 0 1rem 2rem;">
  <h2 id="contract-heading">Canonical contract</h2>
  <p>
    Generated from this component's
    <a href="https://github.com/LilyDesignSystem/lily-design-system/blob/main/components/thinking/AGENTS.md">canonical metadata</a>
    — the machine-checked source the implementations are held to.
  </p>
    <h3>Metadata</h3>
    <ul>
      <li>Component: thinking</li>
      <li>PascalCase: Thinking</li>
      <li>Description: a closed-by-default disclosure for an assistant's reasoning, with a streaming state</li>
      <li>Status: beta — implemented and unit-tested in the Svelte canonical; ports to the other frameworks pending (2026-10-05)</li>
      <li>HTML tag: &lt;details&gt;</li>
      <li>CSS class: .thinking</li>
      <li>Interactive: yes</li>
    </ul>
    <h3>ARIA</h3>
    <ul>
      <li>Native <code>details</code>/<code>summary</code> disclosure semantics</li>
      <li><code>aria-busy="true"</code> on the root only while <code>streaming</code></li>
    </ul>
    <h3>Keyboard</h3>
    <ul>
      <li>Enter: toggles when the summary has focus (native)</li>
      <li>Space: toggles when the summary has focus (native)</li>
      <li>Tab: moves focus to / from the summary</li>
    </ul>
    <h3>Props</h3>
    <ul>
      <li><code>className</code>: string (default: <code>""</code>) -- CSS class name appended to the base class</li>
      <li><code>label</code>: string (required) -- summary text</li>
      <li><code>open</code>: boolean (default: <code>false</code>) -- bindable</li>
      <li><code>streaming</code>: boolean (default: <code>false</code>) -- content is still arriving</li>
      <li><code>children</code>: slot -- the reasoning content</li>
      <li><code>...restProps</code>: unknown -- additional attributes spread onto the <code>&lt;details&gt;</code></li>
    </ul>
</section>
<!-- END generated: canonical contract -->
